import pandas as pd
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
from textblob import TextBlob
import numpy as np

# This file calculates the agreement level of the sentiment scores generated by Vader and TextBlob on the same corpus(HC3)

# Ensure nltk VADER lexicon is downloaded
nltk.download('vader_lexicon')

# Initialize VADER sentiment analyzer
sia = SentimentIntensityAnalyzer()

# Load the CSV file
df = pd.read_csv('D:/Msc/Final Project/HC3 corpus/medicine.csv')

# Define functions for sentiment analysis
def vader_sentiment(text):
    # Using VADER to get compound sentiment score
    return sia.polarity_scores(text)['compound']

def textblob_sentiment(text):
    # Using TextBlob to get polarity score
    return TextBlob(text).sentiment.polarity

# Apply sentiment analysis using VADER and TextBlob to human and ChatGPT answers
df['vader_human'] = df['human_answers'].apply(vader_sentiment)
df['textblob_human'] = df['human_answers'].apply(textblob_sentiment)
df['vader_chatgpt'] = df['chatgpt_answers'].apply(vader_sentiment)
df['textblob_chatgpt'] = df['chatgpt_answers'].apply(textblob_sentiment)

# Function to categorize agreement level based on the differences between scores from two tools
def categorize_agreement(vader_score, textblob_score):
    difference = np.abs(vader_score - textblob_score)
    if difference <= 0.1:
        return 'Agreement'
    elif difference <= 0.5:
        return 'Mild Disagreement'
    else:
        return 'Strong Disagreement'

# Calculate agreement levels for human and ChatGPT answers based on VADER vs TextBlob scores
df['agreement_human'] = df.apply(lambda x: categorize_agreement(x['vader_human'], x['textblob_human']), axis=1)
df['agreement_chatgpt'] = df.apply(lambda x: categorize_agreement(x['vader_chatgpt'], x['textblob_chatgpt']), axis=1)

# Print the DataFrame with sentiments and agreement levels
print(df[['human_answers', 'chatgpt_answers', 'vader_human', 'textblob_human', 'agreement_human', 'vader_chatgpt', 'textblob_chatgpt', 'agreement_chatgpt']])

# Count and print the agreement levels
print("Human Agreement Level Counts:")
print(df['agreement_human'].value_counts())
print("ChatGPT Agreement Level Counts:")
print(df['agreement_chatgpt'].value_counts())
